"""CLI argument definitions for the grasp demo driver.

Kept in one place so flag defaults documented in codex/ task specs and
REPORT_isaac_grasp_env.md stay greppable. Do not change defaults casually —
the P4b-passing V19/V20 commands pin many of these explicitly.
"""
from __future__ import annotations

import argparse


def build_arg_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["press", "pick"], default="press")
    ap.add_argument("--object", choices=["sphere", "cube", "cylinder"], default="sphere")
    ap.add_argument("--object-size", type=float, default=0.015)
    ap.add_argument("--steps", type=int, default=160)
    ap.add_argument("--tactile-every", type=int, default=2)
    ap.add_argument("--tag", default="")
    ap.add_argument("--mu", type=float, default=0.6)
    ap.add_argument("--E", type=float, default=1.0e5)
    ap.add_argument("--ckpt", default="/work/data/assets/vbts_fno/lr_fno_realistic_bc.pt")
    ap.add_argument("--manifest", default="/work/data/assets/ur3e_robotiq_vbts.json")
    ap.add_argument("--cuda", action="store_true")
    ap.add_argument("--no-noise", action="store_true")
    ap.add_argument("--start-isaac", action="store_true", default=True)
    ap.add_argument("--world-camera", action="store_true", default=False)
    ap.add_argument("--livestream", type=int, choices=[0, 1, 2], default=0,
                    help="0=off, 1=native (needs Isaac Sim Native Livestream Client app), "
                         "2=WebRTC (open http://localhost:8211/streaming/webrtc-client in a browser)")
    ap.add_argument("--livestream-hold", type=float, default=60.0)
    ap.add_argument("--tactile-overlay", action=argparse.BooleanOptionalAction, default=False,
                    help="Show live VBTS L/R images in a screen-fixed omni.ui HUD (off by default).")
    ap.add_argument("--tactile-overlay-scale", type=float, default=0.12,
                    help="Legacy compatibility option; ignored by the screen-fixed tactile HUD.")
    ap.add_argument("--tactile-overlay-update-every", type=int, default=1,
                    help="Update overlay every N tactile renders.")
    ap.add_argument("--tactile-overlay-anchor", choices=["robot", "world"], default="robot",
                    help="Legacy compatibility option; ignored by the screen-fixed tactile HUD.")
    ap.add_argument("--make-montage", action=argparse.BooleanOptionalAction, default=True)
    ap.add_argument("--world-camera-width", type=int, default=640)
    ap.add_argument("--world-camera-height", type=int, default=480)
    ap.add_argument("--world-camera-eye", default="1.20,-0.70,0.70")
    ap.add_argument("--world-camera-target", default="0.45,0.22,0.36")
    ap.add_argument("--world-camera-focal-length", type=float, default=24.0)
    ap.add_argument("--world-camera-focus-distance", type=float, default=1.2)
    ap.add_argument("--world-camera-horizontal-aperture", type=float, default=20.955)
    ap.add_argument("--robot-x", type=float, default=0.0)
    ap.add_argument("--robot-y", type=float, default=0.0)
    ap.add_argument("--robot-z", type=float, default=0.0)
    ap.add_argument("--robot-root-rpy-deg", default="0,0,0")
    ap.add_argument("--gripper-target", type=float, default=0.35)
    ap.add_argument("--gripper-open-target", type=float, default=0.0)
    ap.add_argument("--gripper-control-mode", choices=["finger", "all"], default="finger")
    ap.add_argument("--gripper-stiffness", type=float, default=60.0)
    ap.add_argument("--gripper-damping", type=float, default=8.0)
    ap.add_argument("--gripper-effort-limit", type=float, default=5.0)
    ap.add_argument("--passive-gripper-stiffness", type=float, default=0.0)
    ap.add_argument("--passive-gripper-damping", type=float, default=0.0)
    ap.add_argument("--passive-gripper-effort-limit", type=float, default=0.0)
    ap.add_argument("--robot-solver-position-iters", type=int, default=32)
    ap.add_argument("--robot-solver-velocity-iters", type=int, default=8)
    ap.add_argument("--robot-max-depenetration-velocity", type=float, default=0.2)
    ap.add_argument("--gripper-scan-probe", action="store_true")
    ap.add_argument("--gripper-scan-targets", default="0.0,0.05,0.10,0.15,0.20,0.25,0.30,0.35")
    ap.add_argument("--gripper-scan-steps", type=int, default=30)
    ap.add_argument("--gripper-scan-stable-joint-abs", type=float, default=10.0)
    ap.add_argument("--gap-audit", action="store_true")
    ap.add_argument("--gap-audit-targets", default="0.0,0.06,0.12,0.18,0.24")
    ap.add_argument("--gap-audit-settle-steps", type=int, default=30)
    ap.add_argument("--grasp-mode", choices=["legacy", "ik"], default="legacy")
    ap.add_argument("--ik-ee-body-name", default="wrist_3_link")
    ap.add_argument("--ik-home-steps", type=int, default=20)
    ap.add_argument("--ik-pregrasp-steps", type=int, default=60)
    ap.add_argument("--ik-descend-steps", type=int, default=80)
    ap.add_argument("--ik-pregrasp-height", type=float, default=0.08)
    ap.add_argument("--ik-close-force-gate-N", type=float, default=0.3)
    ap.add_argument("--ik-object-settle-steps", type=int, default=20)
    ap.add_argument("--ik-object-offset-world", default="0,0,0")
    # V15 "ride-up compensation": place the cube HIGHER than the measured close-position gel
    # midpoint by this z-offset, so the Robotiq 2F-85 four-bar ride-up (gel pad lifts ~11-14 mm as
    # the finger closes) brings the pads DOWN onto the cube center instead of riding over the top
    # edge and wedging the cube out. Positive = cube above gel midpoint. See memory
    # isaac-grasp-rootcause-v14.
    ap.add_argument("--ik-place-ride-up-offset", type=float, default=0.0)
    ap.add_argument("--ik-pedestal-height", type=float, default=0.345)
    ap.add_argument("--ik-dls-damping", type=float, default=0.08)
    ap.add_argument("--ik-arm-ready-joints", default="0,-1.2,1.4,-1.57,-1.57,0")
    ap.add_argument("--ik-grip-axis-world", default="1,0,0")
    ap.add_argument("--ik-solver", choices=["controller", "weighted-dls", "position-dls"], default="controller")
    ap.add_argument("--ik-position-weight", type=float, default=1.0)
    ap.add_argument("--ik-z-position-weight", type=float, default=4.0)
    ap.add_argument("--ik-orientation-weight", type=float, default=0.30)
    ap.add_argument("--ik-lift-orientation-weight", type=float, default=-1.0)
    ap.add_argument("--ik-hold-orientation-weight", type=float, default=-1.0)
    ap.add_argument("--ik-z-priority-orientation-weight", type=float, default=0.03)
    ap.add_argument("--ik-z-priority-error-m", type=float, default=0.01)
    ap.add_argument("--ik-control-substeps", type=int, default=1)
    ap.add_argument("--ik-max-joint-step", type=float, default=0.12)
    ap.add_argument("--ik-diagnostics-log-every", type=int, default=20)
    ap.add_argument("--ik-preclose-align-steps", type=int, default=40)
    ap.add_argument("--ik-preclose-align-max-m", type=float, default=0.08)
    ap.add_argument("--ik-min-close-ee-z", type=float, default=0.36)
    ap.add_argument("--ik-soft-close-steps", type=int, default=360)
    ap.add_argument("--ik-close-gripper-stiffness", type=float, default=-1.0)
    ap.add_argument("--ik-close-gripper-damping", type=float, default=-1.0)
    ap.add_argument("--ik-close-gripper-effort-limit", type=float, default=-1.0)
    ap.add_argument("--ik-lift-gripper-target-offset", type=float, default=0.0)
    ap.add_argument("--ik-hold-gripper-target-offset", type=float, default=0.0)
    ap.add_argument("--ik-lift-gripper-stiffness", type=float, default=-1.0)
    ap.add_argument("--ik-lift-gripper-damping", type=float, default=-1.0)
    ap.add_argument("--ik-lift-gripper-effort-limit", type=float, default=-1.0)
    ap.add_argument("--ik-hold-gripper-stiffness", type=float, default=-1.0)
    ap.add_argument("--ik-hold-gripper-damping", type=float, default=-1.0)
    ap.add_argument("--ik-hold-gripper-effort-limit", type=float, default=-1.0)
    ap.add_argument("--ik-close-midpoint-probe", action=argparse.BooleanOptionalAction, default=True)
    ap.add_argument("--ik-close-target-from-probe", action=argparse.BooleanOptionalAction, default=True)
    ap.add_argument("--ik-close-target-pen", type=float, default=0.00035)
    ap.add_argument("--ik-place-at-selected-close-target", action=argparse.BooleanOptionalAction, default=True)
    ap.add_argument("--ik-close-midpoint-probe-steps", type=int, default=180)
    ap.add_argument("--ik-close-midpoint-reopen-steps", type=int, default=80)
    ap.add_argument("--ik-live-midpoint-servo", action=argparse.BooleanOptionalAction, default=True)
    ap.add_argument("--ik-live-midpoint-servo-close", action=argparse.BooleanOptionalAction, default=True)
    ap.add_argument("--ik-lift-live-midpoint-servo", action=argparse.BooleanOptionalAction, default=False)
    ap.add_argument("--ik-live-midpoint-servo-gain", type=float, default=0.85)
    ap.add_argument("--ik-live-midpoint-servo-max-step", type=float, default=0.008)
    ap.add_argument("--ik-live-midpoint-servo-max-total", type=float, default=0.14)
    ap.add_argument("--object-at-pads", action="store_true")
    ap.add_argument("--object-pad-z-offset", type=float, default=0.0)
    ap.add_argument("--object-center-solver", choices=["average", "lsq"], default="lsq")
    ap.add_argument("--object-center-tangent-weight", type=float, default=0.0)
    ap.add_argument("--object-center-tangent-x-weight", type=float, default=-1.0)
    ap.add_argument("--object-center-tangent-y-weight", type=float, default=-1.0)
    ap.add_argument("--object-center-offset-world", default="0,0,0")
    ap.add_argument("--live-contact-depth", type=float, default=0.0004)
    ap.add_argument("--place-target-pen", type=float, default=0.00015)
    ap.add_argument("--max-live-contact-depth", type=float, default=0.0005)
    ap.add_argument("--max-live-placement-pen", type=float, default=0.0006)
    ap.add_argument("--live-pose-tactile", action="store_true")
    ap.add_argument("--object-mu", type=float, default=0.9)
    ap.add_argument("--object-mass", type=float, default=0.02)
    ap.add_argument("--friction-combine-mode", choices=["average", "min", "multiply", "max"], default="average")
    ap.add_argument("--object-solver-position-iters", type=int, default=-1)
    ap.add_argument("--object-solver-velocity-iters", type=int, default=-1)
    ap.add_argument("--object-max-depenetration-velocity", type=float, default=-1.0)
    ap.add_argument("--object-contact-offset", type=float, default=2.0e-4)
    ap.add_argument("--object-rest-offset", type=float, default=0.0)
    ap.add_argument("--physics-lift-probe", action="store_true")
    ap.add_argument("--physics-place-closed-probe", action="store_true")
    ap.add_argument("--physics-pedestal-probe", action="store_true")
    ap.add_argument("--physics-pedestal-size", type=float, default=0.04)
    ap.add_argument("--physics-pedestal-height", type=float, default=0.30)
    ap.add_argument("--physics-hold-steps", type=int, default=100)
    ap.add_argument("--physics-close-steps", type=int, default=180)
    ap.add_argument("--physics-close-stop-pen", type=float, default=0.00045)
    ap.add_argument("--physics-grip-pen", type=float, default=0.00045)
    ap.add_argument("--physics-squeeze-margin", type=float, default=0.02)
    ap.add_argument("--physics-squeeze-settle-steps", type=int, default=40)
    ap.add_argument("--physics-squeeze-ramp-steps", type=int, default=8)
    ap.add_argument("--physics-squeeze-object-hold-steps", type=int, default=8)
    ap.add_argument("--physics-squeeze-object-release-pen", type=float, default=-1.0)
    ap.add_argument("--physics-squeeze-pen-check-after-steps", type=int, default=5)
    ap.add_argument("--physics-object-max-depenetration-velocity", type=float, default=0.03)
    ap.add_argument("--physics-force-gate-N", type=float, default=1.0)
    ap.add_argument("--physics-force-spike-limit-N", type=float, default=1.0e4)
    ap.add_argument("--physics-require-force-gate", action=argparse.BooleanOptionalAction, default=True)
    ap.add_argument("--physics-open-clearance", type=float, default=0.002)
    ap.add_argument("--physics-calibrate-close", action="store_true")
    ap.add_argument("--physics-preclose-clearance", type=float, default=0.010)
    ap.add_argument("--physics-preclose-steps", type=int, default=30)
    ap.add_argument("--physics-close-stall-eps", type=float, default=1.0e-5)
    ap.add_argument("--physics-close-stall-steps", type=int, default=20)
    ap.add_argument("--physics-close-log-every", type=int, default=20)
    ap.add_argument("--physics-lift-steps", type=int, default=120)
    ap.add_argument("--physics-lift-height", type=float, default=0.08)
    ap.add_argument("--pseudo-jaw-probe", action="store_true")
    ap.add_argument("--pseudo-jaw-z", type=float, default=0.0)
    ap.add_argument("--pseudo-jaw-open-half-gap", type=float, default=0.0)
    ap.add_argument("--pseudo-jaw-close-half-gap", type=float, default=0.0)
    ap.add_argument("--pseudo-jaw-indent", type=float, default=0.0015)
    ap.add_argument("--pseudo-jaw-pitch-deg", type=float, default=0.0)
    ap.add_argument("--pseudo-jaw-support-probe", action="store_true")
    ap.add_argument("--pseudo-jaw-preclose-settle-steps", type=int, default=-1)
    ap.add_argument("--pseudo-jaw-close-steps", type=int, default=80)
    ap.add_argument("--pseudo-jaw-lift-steps", type=int, default=120)
    ap.add_argument("--pseudo-jaw-lift-height", type=float, default=0.09)
    return ap
